// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCWujCoF7ymq1GeRASqEKGimAqtO1Vuj0',
    appId: '1:453900936160:web:8598939dd58421aed9c185',
    messagingSenderId: '453900936160',
    projectId: 'private-4t',
    storageBucket: 'private-4t.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCWujCoF7ymq1GeRASqEKGimAqtO1Vuj0',
    appId: '1:453900936160:android:8598939dd58421aed9c185',
    messagingSenderId: '453900936160',
    projectId: 'private-4t',
    storageBucket: 'private-4t.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTZ_Jj52HCkvBc9wpkGGnaFUdrZAj037w',
    appId: '1:453900936160:ios:852036549c57e2bbd9c185',
    messagingSenderId: '453900936160',
    projectId: 'private-4t',
    storageBucket: 'private-4t.firebasestorage.app',
    iosBundleId: 'com.private-4t.app',
  );
}
