// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCWujCoF7ymq1GeRASqEKGimAqtO1Vuj0',
    appId: '1:453900936160:web:8598939dd58421aed9c185',
    messagingSenderId: '453900936160',
    projectId: 'private-4t',
    storageBucket: 'private-4t.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr-f25Vha8GPJ_rr3mpA6kROoVqpSmde8',
    appId: '1:890348085959:android:7badf0d793dd9956a354e2',
    messagingSenderId: '890348085959',
    projectId: 'private-4t26',
    storageBucket: 'private-4t26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYcNlXVEp3UafzTF0LEdqNYgBJg2p3W3k', // From plist API_KEY
    appId:
        '1:890348085959:ios:12a8ba2e32c33937a354e2', // From plist GOOGLE_APP_ID
    messagingSenderId: '890348085959',
    projectId: 'private-4t26',
    storageBucket: 'private-4t26.firebasestorage.app',
    iosBundleId: 'com.private-4t.app',
  );
}
